version: 2

updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"

  # GitHub Actions versions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
    commit-message:
      prefix: "ci"
    labels:
      - "ci"
